Name:           ros-lunar-ompl
Version:        1.3.5
Release:        0%{?dist}
Summary:        ROS ompl package

Group:          Development/Libraries
License:        BSD
URL:            http://ompl.kavrakilab.org
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       eigen3-devel
BuildRequires:  boost-devel
BuildRequires:  cmake
BuildRequires:  eigen3-devel
BuildRequires:  pkgconfig

%description
OMPL is a free sampling-based motion planning library.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Mon May 28 2018 Mark Moll <mmoll@rice.edu> - 1.3.5-0
- Autogenerated by Bloom

* Mon May 28 2018 Mark Moll <mmoll@rice.edu> - 1.3.4-0
- Autogenerated by Bloom

* Sat May 26 2018 Mark Moll <mmoll@rice.edu> - 1.3.3-4
- Autogenerated by Bloom

* Wed May 23 2018 Mark Moll <mmoll@rice.edu> - 1.3.2-3
- Autogenerated by Bloom

* Sun Nov 12 2017 Mark Moll <mmoll@rice.edu> - 1.3.2-2
- Autogenerated by Bloom

* Sun Nov 12 2017 Mark Moll <mmoll@rice.edu> - 1.3.2-1
- Autogenerated by Bloom

* Thu May 25 2017 Mark Moll <mmoll@rice.edu> - 1.3.1-3
- Autogenerated by Bloom

* Tue May 23 2017 Mark Moll <mmoll@rice.edu> - 1.3.1-2
- Autogenerated by Bloom

* Fri May 05 2017 Mark Moll <mmoll@rice.edu> - 1.3.0-1
- Autogenerated by Bloom

