Name:           ros-melodic-ompl
Version:        1.4.2
Release:        2%{?dist}
Summary:        ROS ompl package

Group:          Development/Libraries
License:        BSD
URL:            http://ompl.kavrakilab.org
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python2-devel
Requires:       eigen3-devel
BuildRequires:  boost-devel
BuildRequires:  boost-python2-devel
BuildRequires:  cmake
BuildRequires:  eigen3-devel
BuildRequires:  pkgconfig

%description
OMPL is a free sampling-based motion planning library.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Wed Jun 26 2019 Mark Moll <mmoll@rice.edu> - 1.4.2-2
- Autogenerated by Bloom

* Wed Jun 26 2019 Mark Moll <mmoll@rice.edu> - 1.4.2-1
- Autogenerated by Bloom

* Fri Jan 18 2019 Mark Moll <mmoll@rice.edu> - 1.4.2-0
- Autogenerated by Bloom

* Wed Dec 05 2018 Mark Moll <mmoll@rice.edu> - 1.4.1-0
- Autogenerated by Bloom

* Sun Jul 01 2018 Mark Moll <mmoll@rice.edu> - 1.4.0-1
- Autogenerated by Bloom

* Mon May 14 2018 Mark Moll <mmoll@rice.edu> - 1.4.0-0
- Autogenerated by Bloom

