%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-ompl
Version:        1.4.2
Release:        5%{?dist}
Summary:        ROS ompl package

License:        BSD
URL:            http://ompl.kavrakilab.org
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python2-devel
Requires:       boost-python3-devel
Requires:       eigen3-devel
BuildRequires:  boost-devel
BuildRequires:  boost-python2-devel
BuildRequires:  boost-python3-devel
BuildRequires:  cmake
BuildRequires:  eigen3-devel
BuildRequires:  pkgconfig

%description
OMPL is a free sampling-based motion planning library.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Wed Dec 11 2019 Mark Moll <mmoll@rice.edu> - 1.4.2-5
- Autogenerated by Bloom

* Wed Dec 11 2019 Mark Moll <mmoll@rice.edu> - 1.4.2-4
- Autogenerated by Bloom

* Wed Nov 27 2019 Mark Moll <mmoll@rice.edu> - 1.4.2-3
- Autogenerated by Bloom

* Wed Jun 26 2019 Mark Moll <mmoll@rice.edu> - 1.4.2-2
- Autogenerated by Bloom

* Wed Jun 26 2019 Mark Moll <mmoll@rice.edu> - 1.4.2-1
- Autogenerated by Bloom

* Fri Jan 18 2019 Mark Moll <mmoll@rice.edu> - 1.4.2-0
- Autogenerated by Bloom

* Wed Dec 05 2018 Mark Moll <mmoll@rice.edu> - 1.4.1-0
- Autogenerated by Bloom

* Sun Jul 01 2018 Mark Moll <mmoll@rice.edu> - 1.4.0-1
- Autogenerated by Bloom

* Mon May 14 2018 Mark Moll <mmoll@rice.edu> - 1.4.0-0
- Autogenerated by Bloom

